name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Run lint test
        run: |
          devbox run -- task lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true
      - name: Run python test
        env:
          PAPERLESS_URL: ${{ secrets.PAPERLESS_URL }}
          PAPERLESS_API_KEY: ${{ secrets.PAPERLESS_API_KEY }}
          PAPERLESS_TEST_CORRESPONDENT: Aldi
          PAPERLESS_TEST_DOCUMENT_TYPE: Kassenbon
          PAPERLESS_TEST_YEAR: 2024
          PAPERLESS_TEST_MONTH: 7
          PAPERLESS_TEST_TAG: Discounter
        run: |
          devbox run -- task test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.repository_owner == 'jleine' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true
      - uses: bjoluc/semantic-release-config-poetry@v2
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}