name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Cache Devbox dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/devbox
            ~/.cache/nix
          key: ${{ runner.os }}-devbox-${{ hashFiles('devbox.json') }}
          restore-keys: |
            ${{ runner.os }}-devbox-

      - name: Run lint test
        run: |
          devbox run -- task lint