name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up cache for Devbox dependencies
        uses: actions/cache@v3
        with:
          path: ~/.devbox/cache
          key: ${{ runner.os }}-devbox-${{ hashFiles('devbox.toml') }}
          restore-keys: |
            ${{ runner.os }}-devbox-

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Run python test
        env:
          PAPERLESS_URL: ${{ secrets.PAPERLESS_URL }}
          PAPERLESS_API_KEY: ${{ secrets.PAPERLESS_API_KEY }}
          PAPERLESS_TEST_CORRESPONDENT: Aldi
          PAPERLESS_TEST_DOCUMENT_TYPE: Kassenbon
          PAPERLESS_TEST_YEAR: 2024
          PAPERLESS_TEST_MONTH: 7
          PAPERLESS_TEST_TAG: Discounter
        run: |
          devbox run -- task test