name: Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Run python test
        env:
          PAPERLESS_URL: ${{ secrets.PAPERLESS_URL }}
          PAPERLESS_API_KEY: ${{ secrets.PAPERLESS_API_KEY }}
          PAPERLESS_TEST_CORRESPONDENT: ${{ secrets.PAPERLESS_TEST_CORRESPONDENT }}
          PAPERLESS_TEST_DOCUMENT_TYPE: ${{ secrets.PAPERLESS_TEST_DOCUMENT_TYPE }}
          PAPERLESS_TEST_MONTH: ${{ secrets.PAPERLESS_TEST_MONTH }}
          PAPERLESS_TEST_TAG: ${{ secrets.PAPERLESS_TEST_TAG }}
          PAPERLESS_TEST_YEAR: ${{ secrets.PAPERLESS_TEST_YEAR }}
        run: |
          devbox run -- task test